"""Export the flood facts the assistant may state, from the reports that hold them.

    python scripts/export_flood_facts.py            # write
    python scripts/export_flood_facts.py --check    # fail if the file is stale

The serving plane is bundled from ``backend/`` alone, so it cannot open
``ml/experiments`` or ``models/`` at request time. The alternative -- typing the
numbers into the tool module -- is how a model card ends up quoting a score
from a run that was later superseded. So the numbers are copied here, by code,
from the files that measured them, and ``--check`` (run by the test suite)
fails the moment the copy and the source disagree.

Every value in the output names the file it came from. Nothing is computed
here except sums of counts that are already in those files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT = REPO_ROOT / "backend" / "api" / "flood_facts.generated.json"

MANIFEST = "models/flood/train_manifest_loro_india_sar_ratio.json"
TEST_REPORT = "ml/experiments/flood_unet/test_loro_india_sar_ratio.json"
COMPARISON = "ml/experiments/flood_comparison.json"
OTSU_REPORT = "ml/experiments/flood_baseline/sweep_0.66/otsu_baseline.json"
GATE_MODULE = "satai/ml/distribution_gate.py"
INFER_MODULE = "ml/flood/infer_scene.py"
RISK_CONFIG = "configs/risk.yaml"
SENSITIVITY_GLOB = "ml/experiments/risk_sensitivity/sensitivity_rho*.json"


def _load(relative: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads((REPO_ROOT / relative).read_text(encoding="utf-8"))
    return data


def _risk() -> dict[str, Any]:
    """Default exponents and the C4 sensitivity extremes, from their sources.

    The extremes are taken over every correlation setting that was run, so the
    figure quoted is the worst case the experiment found, not a favourable one.
    """
    import yaml

    config = yaml.safe_load((REPO_ROOT / RISK_CONFIG).read_text(encoding="utf-8"))
    exponents = {k: float(v) for k, v in config["formulation"]["exponents"].items()}
    reports = sorted(REPO_ROOT.glob(SENSITIVITY_GLOB))
    summaries = [json.loads(p.read_text(encoding="utf-8"))["summary"] for p in reports]
    grid = config["sensitivity_analysis"]["parameters"]["alpha"]
    return {
        "formulation": "R = H^alpha * E^beta * V^gamma (ADR-008)",
        "default_exponents": exponents,
        "c4_sensitivity": {
            "exponent_grid": grid,
            "n_settings": len(reports),
            "min_spearman_rank_correlation": round(
                min(s["min_rank_correlation"] for s in summaries), 3
            ),
            "max_band_reassignment_percent": round(
                100 * max(s["max_band_reassignment"] for s in summaries), 1
            ),
        },
        "source": [RISK_CONFIG, SENSITIVITY_GLOB],
    }


def build() -> dict[str, Any]:
    from ml.flood.infer_scene import OVERLAP, TILE

    from satai.ml import distribution_gate as gate
    from satai.preprocessing.splits import BOLIVIA

    manifest = _load(MANIFEST)
    test = _load(TEST_REPORT)
    comparison = _load(COMPARISON)
    otsu = _load(OTSU_REPORT)

    sizes = manifest["sizes"]
    regions = sorted(otsu["per_region"])
    reserved = otsu["per_region"][BOLIVIA]["n_chips"]
    hyper = manifest["hyperparameters"]
    headline = test["headline"]

    return {
        "_comment": (
            "Generated by scripts/export_flood_facts.py from the reports named in "
            "each 'source'. Do not edit by hand; tests fail if this drifts."
        ),
        "dataset": {
            "name": "Sen1Floods11 v1.1 HandLabeled",
            "n_chips": sizes["train"] + sizes["val"] + sizes["test"] + reserved,
            "n_events": len(regions),
            "events": regions,
            "chip_size_px": TILE,
            "split": {
                "protocol": manifest["protocol"],
                "fold": manifest["fold"],
                "region_disjoint": manifest["region_disjoint"],
                "train_chips": sizes["train"],
                "validation_region": manifest["val_regions"],
                "validation_chips": sizes["val"],
                "test_region": manifest["test_regions"],
                "test_chips": sizes["test"],
                "reserved_region": BOLIVIA,
                "reserved_chips": reserved,
            },
            "source": [MANIFEST, OTSU_REPORT],
        },
        "ground_truth": {
            "name": "Sen1Floods11 LabelHand",
            "what": "hand-annotated water masks distributed with Sen1Floods11",
            "values": {"1": "water", "0": "not water", "-1": "not annotated"},
            "unannotated_handling": (
                "Pixels labelled -1 are excluded from the loss and from every "
                "metric, in both the numerator and the denominator."
            ),
            "not_available_for": (
                "Real scenes run by SAT-AI (for example the Nepal Koshi scene of "
                "2024-09-27) have no ground truth, so nothing produced on them "
                "has been scored."
            ),
            "source": ["ml/flood/dataset.py", "ml/flood/losses.py"],
        },
        "model": {
            "name": "flood_unet",
            "architecture": "U-Net, trained from scratch",
            "depth": manifest["spec"]["depth"],
            "base_width": manifest["spec"]["base_width"],
            "dropout": manifest["spec"]["dropout"],
            "parameters": manifest["n_parameters"],
            "bands": manifest["bands"],
            "loss": {
                "bce_weight": hyper["bce_weight"],
                "dice_weight": hyper["dice_weight"],
                "masked": True,
            },
            "output": "one logit per pixel; sigmoid gives water probability",
            "threshold": test["headline_threshold"],
            "epochs_run": manifest["epochs_run"],
            "batch_size": hyper["batch_size"],
            "learning_rate": hyper["learning_rate"],
            "checkpoint_selected_on": test["selection"]["checkpoint_selected_on"],
            "source": [MANIFEST, TEST_REPORT],
        },
        "metrics": {
            "india_test": {
                "label": "TEST: held-out India, 68 chips, never used for training or selection",
                "region": test["regions"],
                "n_chips": test["n_chips"],
                "iou": headline["iou"],
                "f1": headline["f1"],
                "precision": headline["precision"],
                "recall": headline["recall"],
                "threshold": test["headline_threshold"],
                "per_chip_iou_median": test["per_chip_iou"]["median"],
                "source": TEST_REPORT,
            },
            "mekong_validation": {
                "label": (
                    "VALIDATION: Mekong, used to select the checkpoint. NOT a test "
                    "score and NOT the India score."
                ),
                "region": manifest["val_regions"],
                "n_chips": sizes["val"],
                "iou": round(manifest["best_val_iou"], 4),
                "source": MANIFEST,
            },
            "validation_to_test_gap_iou": comparison["validation_to_test_gap"]["gap"],
            "otsu_india_test": {
                "label": "TEST: classical Otsu baseline on the same 68 India chips",
                "region": [comparison["test_region"]],
                "iou": comparison["baseline"]["iou"],
                "f1": comparison["baseline"]["f1"],
                "precision": comparison["baseline"]["precision"],
                "recall": comparison["baseline"]["recall"],
                "source": COMPARISON,
            },
            "unet_minus_otsu_iou": comparison["delta_iou"],
            "unet_relative_gain_percent": round(100 * comparison["relative_gain"], 1),
        },
        "otsu": {
            "method": comparison["baseline"]["method"],
            "supervised": comparison["baseline"]["supervised"],
            "separability_guard": otsu["min_separability"],
            "hand_mask": False,
            "source": [COMPARISON, OTSU_REPORT],
        },
        "gate": {
            "instrument": "Track A/B distribution gate (ADR-010)",
            "compares": (
                "the scene's per-band pixel distributions against the training "
                "chips the model actually saw"
            ),
            "warn_wasserstein_db": gate.WARN_WASSERSTEIN_DB,
            "fail_wasserstein_db": gate.FAIL_WASSERSTEIN_DB,
            "warn_ks": gate.WARN_KS,
            "fail_ks": gate.FAIL_KS,
            "p_value_used": False,
            "source": GATE_MODULE,
        },
        "risk": _risk(),
        "pipeline": {
            "steps": [
                "Find a Sentinel-1 acquisition over the study area in the Planetary "
                "Computer catalogue.",
                "Read VV and VH over the area and convert linear backscatter to dB.",
                "Compute the VV/VH ratio band (VV dB minus VH dB).",
                "Run the distribution gate against the training chips.",
                "Normalise each band with the training normaliser.",
                f"Predict in {TILE} px tiles with {OVERLAP} px overlap, averaging overlaps.",
                "Apply a sigmoid and threshold the probability to a water mask.",
                "Write probability, mask and extent with the gate verdict attached.",
            ],
            "tile_px": TILE,
            "overlap_px": OVERLAP,
            "not_applied": [
                "HAND terrain mask",
                "permanent-water exclusion",
                "speckle filter",
            ],
            "source": INFER_MODULE,
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args(argv)

    rendered = json.dumps(build(), indent=2) + "\n"
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.name} is stale; run python scripts/export_flood_facts.py")
            return 1
        print(f"{OUTPUT.name} matches its sources")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
