"""Render the landing-page figure from a real held-out India chip.

    python scripts/make_hero_figure.py

The page previously showed an illustration styled as Sentinel-1 output, with
two different dates on it and coordinates in central Europe. A flood-mapping
project cannot show a picture of flood mapping it did not do. This draws what
the trained model actually produced on a chip it never saw: VV backscatter, the
Sen1Floods11 hand label, and the U-Net prediction coloured against that label.

**Which chip.** Not the best one. Among India test chips with enough labelled
water to be legible, the one whose own IoU is closest to the pooled test IoU
is chosen, and its IoU is printed on the page beside the per-chip median, so a
reader can see both how typical it is and how much chips vary.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import numpy as np  # noqa: E402
import torch  # noqa: E402
from ml.flood.dataset import FloodChips, selection_for_bands  # noqa: E402
from ml.flood.evaluate import DEFAULT_DATA, load_checkpoint  # noqa: E402
from ml.flood.train import select_fold  # noqa: E402

CHECKPOINT = REPO_ROOT / "models/flood/flood_unet_loro_india_sar_ratio_best.pt"
TEST_REPORT = REPO_ROOT / "ml/experiments/flood_unet/test_loro_india_sar_ratio.json"
OUT_IMAGE = REPO_ROOT / "frontend/public/hero_india_chip.png"
OUT_META = REPO_ROOT / "frontend/lib/hero-chip.generated.json"

#: Minimum labelled-water fraction for a chip to be a usable illustration. A
#: chip that is 1 % water shows nothing at page scale, whatever its score.
MIN_WATER = 0.08


def main() -> int:
    from PIL import Image

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, normalizer, payload = load_checkpoint(CHECKPOINT, device)
    model.eval()
    fold = select_fold(DEFAULT_DATA, payload["fold"])
    chips = list(fold.test)
    dataset = FloodChips(
        chips, DEFAULT_DATA, normalizer, with_ratio=selection_for_bands(payload["bands"])
    )
    pooled = json.loads(TEST_REPORT.read_text(encoding="utf-8"))
    pooled_iou = pooled["headline"]["iou"]
    median_iou = pooled["per_chip_iou"]["median"]

    candidates = []
    with torch.no_grad():
        for index, chip in enumerate(chips):
            stack, target, valid = dataset[index]
            prob = torch.sigmoid(model(stack[None].to(device)))[0, 0].cpu().numpy()
            truth = target[0].numpy() > 0.5
            ok = valid[0].numpy() > 0.5
            pred = prob >= 0.5
            water = truth[ok].mean() if ok.any() else 0.0
            inter = (pred & truth & ok).sum()
            union = ((pred | truth) & ok).sum()
            if water < MIN_WATER or union == 0:
                continue
            candidates.append(
                (
                    abs(inter / union - pooled_iou),
                    index,
                    chip,
                    inter / union,
                    water,
                    pred,
                    truth,
                    ok,
                )
            )

    _, index, chip, iou, water, pred, truth, ok = min(candidates, key=lambda c: c[0])
    features, _labels, _valid = dataset.reader.load(chip)
    vv = np.where(ok, features[0], np.nan)

    def rgb(hexes: list[str]) -> np.ndarray:
        return np.array([[int(h[i : i + 2], 16) for i in (1, 3, 5)] for h in hexes], np.uint8)

    lo, hi = np.nanpercentile(vv, [2, 98])
    grey = np.clip((np.nan_to_num(vv, nan=lo) - lo) / (hi - lo) * 255, 0, 255).astype(np.uint8)
    radar = np.stack([grey] * 3, axis=-1)
    radar[~ok] = rgb(["#334155"])[0]

    label = rgb(["#111827", "#38bdf8", "#334155"])[np.where(ok, truth.astype(int), 2)]

    # 0 dry agreed, 1 water agreed, 2 missed water, 3 false water, 4 unlabelled
    agreement = np.select(
        [~ok, pred & truth, ~pred & truth, pred & ~truth], [4, 1, 2, 3], default=0
    )
    compared = rgb(["#111827", "#38bdf8", "#f59e0b", "#f43f5e", "#334155"])[agreement]

    gap = 16
    size = radar.shape[0]
    canvas = np.zeros((size, size * 3 + gap * 2, 3), np.uint8)
    canvas[:] = rgb(["#0b1220"])[0]
    for i, panel in enumerate((radar, label, compared)):
        canvas[:, i * (size + gap) : i * (size + gap) + size] = panel
    OUT_IMAGE.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(canvas).save(OUT_IMAGE, optimize=True)

    meta = {
        "_comment": "Generated by scripts/make_hero_figure.py. Do not edit by hand.",
        "chip": chip.key,
        "region": chip.region,
        "partition": "test (held out from training and checkpoint selection)",
        "chip_iou": round(float(iou), 3),
        "labelled_water_fraction": round(float(water), 3),
        "pooled_test_iou": pooled_iou,
        "per_chip_median_iou": median_iou,
        "selection": (
            "the India test chip with at least 8% water whose IoU is closest to the pooled IoU"
        ),
        "image": "/hero_india_chip.png",
    }
    OUT_META.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(meta, indent=2))
    size_kb = OUT_IMAGE.stat().st_size // 1024
    print(f"chips considered: {len(candidates)} of {len(chips)}; image {size_kb} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
